import Head from "next/head";
import Image from "next/image";

import Featured from "../components/Featured";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sanatan Astrology</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="Keywords"
          content=" Vedic Astrology Services in English, Czech and Spanish Languages"
        />
        <link rel="icon" href="/img/logosvg.svg" />
      </Head>
      <Featured />
    </div>
  );
}
